// @flow
// flow-typed signature: 90acd3db9fd69cf4b93825c5babd0523
// flow-typed version: <<STUB>>/@fortawesome/react-fontawesome_v0.1.4/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@fortawesome/react-fontawesome'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@fortawesome/react-fontawesome' {
  declare export var FontAwesomeIcon: React$ComponentType<any>;
}
declare module '@fortawesome/fontawesome-svg-core' {
  declare module.exports: any;
}
declare module '@fortawesome/free-brands-svg-icons' {
  declare module.exports: any;
}
declare module '@fortawesome/free-regular-svg-icons' {
  declare module.exports: any;
}
declare module '@fortawesome/free-solid-svg-icons' {
  declare module.exports: any;
}
// declare module '@fortawesome/pro-light-svg-icons' {
//   declare module.exports: any;
// }
// declare module '@fortawesome/pro-regular-svg-icons' {
//   declare module.exports: any;
// }
// declare module '@fortawesome/pro-solid-svg-icons' {
//   declare module.exports: any;
// }
