name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - ([ -n "$ENV_TEST" ] && echo "$ENV_TEST" > .env.yml) || (echo "No env data"; exit 1)
    - yarn --frozen-lockfile
    - ./tasker info
    - ./tasker test
    - ./tasker build-everything --production

